### PR TITLE
Support current versions of Node.js

### PR DESCRIPTION
**Pull request by phlipper**
This PR adds snippets for installing Node.js versions `6.x` and `7.x`, including support for updating from previous versions if present.

### CODE REVIEW

**Comment by lvangool** [comment]
Thanks for submitting this @phlipper! Wouldnt it make more sense to handle the different versions via an ENV var (instead of multiple snippets per version?)

**Comment by phlipper** [comment]
@lvangool I was following the convention of the existing files, but I would be happy to collapse all of those down into a single script which can utilize an ENV var if you'd prefer.

**Comment by lvangool** [comment]
@phlipper Got it! Yes that would be great to collapse them down.
(leaving the existing ones in place for legacy stacks)

**Comment by nicdal** [comment]
Is there a way to handle the different versions via ENV now? or was it never implemented?

**Pull request closed without merging**
